services:
  postgres:
    image: postgres:16
    container_name: dividas
    environment:
      POSTGRES_DB: dividas
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: